### ISSUE TITLE
Fatal error reported.

### ISSUE THREAD

**Issue by jalvesnicacio** [deguilardi/android_project_prop_tracker#1]
Fatal error: Access level to GradleFile::__construct() must be public (as in class GitFile) in /home/vagrant/code/andtracking/classes/GradleFile.php on line 6

PHP Version: 7.1.32-1+ubuntu18.04.1+deb.sury.org+1

![Captura de tela de 2019-11-06 08-55-33](https://user-images.githubusercontent.com/2067136/68304333-891f7280-0073-11ea-9c5c-8ebd11f2e252.png)

**Comment by deguilardi** [comment]
fixed!
